FROM python:3.6

MAINTAINER Stef sstefin@bk.ru

COPY requirements.txt /app/

WORKDIR ./app/

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

RUN python manage.py test

CMD ["python", "manage.py", "test"]
